spring:
  profiles:
    active: dev
  datasource:
    druid:
      initial-size: 1
      min-idle: 1
      max-active: 20
      test-on-borrow: true
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-While-Idle: true
      test-on-return: false
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: 20
      filters: stat,wall,config
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000;config.decrypt=false
      monitor:
        enabled: enabled # 配置此属性Monitor才生效
        druid-stat-view: /druid/*
        druid-web-stat-filter: /*
        allow: 127.0.0.1
        deny:
        login-username: admin
        login-password: 123456
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'
        reset-enable: false
server:
  port: 8090
logging:
  config: classpath:logback-spring.xml
  path: logs/
  file: fastboot
fastboot:
    security:
        authentication:
            jwt:
                # This token must be encoded using Base64 and be at least 256 bits long (you can type `openssl rand -base64 64` on your command line to generate a 512 bits one)
                base64-secret: Y2FkNjY0ZGQ2MzkzOTc3NDcxMmY2M2NmODI2OGUzYTNkMzZhNzg4ZjFlNDI3YThiNWMzMjQwNDJiN2ViMTczMzcxYjczOGM4ODFlODUyZDkwYjFjOWEyMWRkMjgyODk3MzM0ODQyN2E0MjcxZTAzNGMxNWFiZjVlODZjMTg1NGM=
                # Token is valid 24 hours
                token-validity-in-seconds: 86400
                # 30 days
                token-validity-in-seconds-for-remember-me: 2592000
mybatis:
  mapper-locations: classpath:mapper/**/*.xml

